/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matias Boldini
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Talleres = new javax.swing.JButton();
        Viajes = new javax.swing.JButton();
        ActiRecrea = new javax.swing.JButton();
        DescJubilados = new javax.swing.JButton();
        EncuCharJor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Socios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido al menú del centro de jubliados");

        Talleres.setText("Talleres");
        Talleres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TalleresActionPerformed(evt);
            }
        });

        Viajes.setText("Viajes");
        Viajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViajesActionPerformed(evt);
            }
        });

        ActiRecrea.setText("Actividades recreativas");

        DescJubilados.setText("Descuentos para jubilados");

        EncuCharJor.setText("Encuentros, charlas y jornadas");

        jLabel2.setText("Elija el botón el cual quiera obtener información");

<<<<<<< HEAD
        jButton6.setText("Socios");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
=======
        Socios.setText("Socios");
>>>>>>> c4e6401a62b37a99d14dee78f5826719f4169202

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DescJubilados)
                                .addGap(18, 18, 18)
                                .addComponent(EncuCharJor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Talleres)
                                .addGap(18, 18, 18)
                                .addComponent(Viajes)
                                .addGap(18, 18, 18)
<<<<<<< HEAD
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
=======
                                .addComponent(ActiRecrea)
                                .addGap(18, 18, 18)
                                .addComponent(Socios))))
>>>>>>> c4e6401a62b37a99d14dee78f5826719f4169202
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
<<<<<<< HEAD
                .addContainerGap(39, Short.MAX_VALUE))
=======
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> c4e6401a62b37a99d14dee78f5826719f4169202
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Talleres)
                    .addComponent(Viajes)
                    .addComponent(ActiRecrea)
                    .addComponent(Socios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescJubilados)
                    .addComponent(EncuCharJor))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViajesActionPerformed

    private void TalleresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TalleresActionPerformed
        // TODO add your handling code here:
        Talleres talleres=new Talleres();
        talleres.setVisible(true);
        
<<<<<<< HEAD
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Socios socios=new Socios();
        socios.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

=======
    }//GEN-LAST:event_TalleresActionPerformed
                                                                                                                                                                                
>>>>>>> c4e6401a62b37a99d14dee78f5826719f4169202
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActiRecrea;
    private javax.swing.JButton DescJubilados;
    private javax.swing.JButton EncuCharJor;
    private javax.swing.JButton Socios;
    private javax.swing.JButton Talleres;
    private javax.swing.JButton Viajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
